name: push-artifact

on:
  push:
    branches:
      - 'main'

permissions:
  packages: write # needed for ghcr.io access

env:
  OCI_REPO: "oci://ghcr.io/den-vasyliev/${{ github.event.repository.name }}"

jobs:
  kubernetes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      #   with:
      #     repository: den-vasyliev/flux-gitops-orig
      #     token: ${{ secrets.GITHUB_TOKEN }}
      # - name: Setup Flux CLI
      #   uses: fluxcd/flux2/action@main
      # - name: Login to GHCR
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      # - name: Push manifests
      #   run: |
      #     flux push artifact $OCI_REPO:$(git rev-parse --short HEAD) \
            # --path="./clusters/demo" \
            # --source="$(git config --get remote.origin.url)" \
            # --revision="$(git branch --show-current)@sha1:$(git rev-parse HEAD)"
